### PR TITLE
Layout changes

### PR DESCRIPTION
**Pull request by emilianya**
This will probably be the final update to prod before launch

### CODE REVIEW

**Comment by ivyturner** [comment]
no worky with dark reader (michael edge 114.0.1823.58, Dark Reader version 4.9.64)

**Comment by emilianya** [comment]
> no worky with dark reader (michael edge 114.0.1823.58, Dark Reader version 4.9.64)

explain harder than no worky, screenshit?

**Comment by emilianya** [comment]
also my sister in christ this site has darkmode built in

**Comment by ivyturner** [comment]
forgor screenshat but it Works, just not exactly how it does without and i thought i'd just make you aware

image

**Comment by emilianya** [comment]
wow what a silly extension, removing my bright colors on a dark background

**Comment by ivyturner** [comment]
> also my sister in christ this site has darkmode built in

i have it on for everything* so my eyes dont get toasted viewing Webbed Sites

already going blind, dont need it happening faster

**Comment by emilianya** [comment]
> > also my sister in christ this site has darkmode built in
> 
> i have it on for everything* so my eyes dont get toasted viewing Webbed Sites

they really should make it not do that when there is css that looks at the system preferred theme

**Comment by ivyturner** [comment]
wen released i will add it to the [Already Dark Mode list](https://github.com/darkreader/darkreader/blob/main/src/config/dark-sites.config) but you can also do [this, apparently](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#adding-a-website-that-is-already-dark)

**Comment by emilianya** [comment]
> The entire website, including all subpages, is dark by default, regardless of the system's preferred color scheme.

I default to preferred color scheme

**Pull request merged**
